accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('/signup', views.signup, name="signup"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.article_list, name='list'),
    path('<slug:slug>', views.article_detail, name="detail"),
]

djangoblog/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home),
    path('accounts', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('about/', views.about),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    #show the title when showing an instance
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

accounts/views.py
from django.shortcuts import render

# Create your views here.
def signup(request):
    return render(request, "accounts/signup.html")

articles/views.py
from django.shortcuts import render
from .models import Article

def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

djangoblog/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<h1> Sign up </h1>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} 

{% block content %}

<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>

{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} 

{% block content %}

  <h1>Articles</h1>
  <div class="articles">
  {% for article in articles %}
    <div class="article">
      <h2><a href='{% url 'articles:detail' slug=article.slug %}'> {{ article.title }} </a></h2>
      <p> {{ article.snippet }} </p>
      <p> {{ article.date }} </p>
    </div>
  {% endfor %}

{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About</title>
</head>
<body>

    <h1>About</h1>

</body>
</html>

templates/base_layout.html
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Articles</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}"
</head>
<body>

    <div class="wrapper">
    <h1><a href="{% url 'articles:list' %}">
      <div class='logo'>
        <img src="{% static 'logo.png' %}"
      </div>
    </a></h1>
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
</head>
<body>

    <h1>Home</h1>

</body>
</html>